import { realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate as drizzleMigrate } from 'drizzle-orm/node-postgres/migrator';
import { createDb, databaseUrl, redactConnectionString } from './client.js';
import type { DbClient } from './client.js';

/** The committed SQL migrations, generated by `pnpm -F @agon/db db:generate`. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));

/** Advisory lock key so concurrent starters (server replicas, test workers) migrate one at a time. */
export const MIGRATION_LOCK_KEY = 0x6167_6f6e;

/**
 * Applies pending migrations. Serialised through a session-level advisory lock held on one
 * dedicated connection, which is also the connection the migrator runs on.
 */
export async function migrate(db: DbClient): Promise<void> {
  const client = await db.$client.connect();
  try {
    await client.query('select pg_advisory_lock($1)', [MIGRATION_LOCK_KEY]);
    try {
      await drizzleMigrate(drizzle(client), { migrationsFolder: MIGRATIONS_FOLDER });
    } finally {
      await client.query('select pg_advisory_unlock($1)', [MIGRATION_LOCK_KEY]);
    }
  } finally {
    client.release();
  }
}

/** Connects, migrates and disconnects. */
export async function migrateDatabase(connectionString: string): Promise<void> {
  const handle = createDb(connectionString, { pool: { max: 2 } });
  try {
    await migrate(handle.db);
  } finally {
    await handle.close();
  }
}

function isMainModule(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isMainModule()) {
  const url = databaseUrl();
  migrateDatabase(url)
    .then(() => {
      process.stdout.write(`migrations applied: ${redactConnectionString(url)}\n`);
    })
    .catch((error: unknown) => {
      const message = error instanceof Error ? error.message : String(error);
      process.stderr.write(`migration failed for ${redactConnectionString(url)}: ${message}\n`);
      process.exitCode = 1;
    });
}
